name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [qaterial-update]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - docker-image: 'reivilo1234/qt-webassembly-cmake:qt5.15-em1.39.8'

    steps:
    -
      uses: actions/checkout@v2
    -
      name: "🔧 Configure"
      run: |
        mkdir -p build                                                                  && \
        docker run --rm -v $(pwd):/src/ -u $(id -u):$(id -g) ${{ matrix.docker-image }}    \
          cmake                                                                            \
          -DQATERIALONLINE_BUILD_RUN_NUMBER=${{ github.run_number }}                       \
          -DQATERIALONLINE_BUILD_RUN_ID=${{ github.run_id }}                               \
          -DQATERIAL_ENABLE_PCH=OFF                                                        \
          -DQATERIAL_ENABLE_UNITY_BUILD=OFF                                                \
          -B ./build/ -S .
    -
      name: "🔨 Build"
      run: |
        docker run --rm -v $(pwd):/src/ -u $(id -u):$(id -g) ${{ matrix.docker-image }} \
          make -C build -j
    -
      name: "🚀 Deploy"
      run: |
        cd build/deploy
        git init
        git add .
        git -c user.name='ci' -c user.email='ci' commit -m init
        git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages
      if: (github.event_name == 'repository_dispatch') || (github.event_name == 'push' && github.ref == 'refs/heads/master')
